name: Format
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Format DNA Frontend
        run: npm ci && npm run format
        working-directory: dna-frontend
      - name: Format DNA Backend
        run: npm ci && npm run format
        working-directory: dna-backend

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install pre-commit
        run: pip install pre-commit
        working-directory: dna-advisor
      - name: Unsetting core.hooksPath
        run: git config --unset-all core.hooksPath
      - name: Install pre-commit hooks
        run: pre-commit install
      - name: Run pre-commit Hooks
        run: pre-commit run --all-files

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
