name: Format
on:
  pull_request:
    branches: [devops/actions]
  push:
    branches: [devops/actions]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ACTIONS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          token: ${{ secrets.ACTIONS_TOKEN }}
      - run: cd /dna-frontend
      - run: npm ci
      - run: npm run format
      - run: cd /dna-backend
      - run: npm ci
      - run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
