name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    - name: ng build
      run: |
        cd dna-frontend
        npm ci
        npm start &
        sleep 30
    # Might want to run backend + LLM here eventually; current setup runs fine without it
    - name: Install dependencies
      working-directory: ./testing
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./testing
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./testing
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30